# Generated by Django 5.2.2 on 2025-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_rename_acess_token_jiratoken_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiratoken',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jiratoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
